config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

  resources :user

end

app/models/album.rb
class Album < ActiveRecord::Base
  belong_to :artist
  has_many :tracks
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums
  
end

app/models/listen.rb
class Listen < ActiveRecord::Base
  belongs_to :user
  belongs_to :track
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_many :listens
  has_many :users, through: :listens
end

app/models/user.rb
require 'rockstar'

class User < ActiveRecord::Base
  has_many :listens
  has_many :tracks, through: :listens
  #attr_accessor :username
  #validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end

	def show
	end
end

app/controllers/user_controller.rb
require 'rockstar'
class UserController < ApplicationController

  def new
    p "CHUJUF STO"
    Rockstar.lastfm = {:api_key => "91c64969c5a00f5ea3cceb3c3d9467ee", :api_secret => "488c18ee374e12d3fe05e41fbea31399"}
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create(user)
    user.save
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= form_tag("/show", method: "get") do %>
  <%= label_tag(:q, "Username:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Get Data!") %>
<% end %>

app/views/home/show.html.erb
<h1> TUTAJ DANE Z LASTA </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicStats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/new.html.erb
<% @user = User.new %>
<% @user.id = 1 %>

<%= form_for @user, url: edit_user_path(@user) do |u| %>
  <%= u.label :username %>:
  <%= u.text_field :name %><br />

  <%= u.submit %>
<% end %>